### PR TITLE
adding more functionality for howlerjs 2.0-beta

### PR DESCRIPTION
**Pull request by KnightMearh**
Howl.hx:
- toggled some properties as optional
- cleaned up volume overloads based on loop() and seek() setup. What's the best way to handle the implementations for these three funcs?
- renamed some vars to match doc comments
- changed event callback type (on, off, once) to Dynamic in order to support Void->Void and Int->Void as options

HowlOptions
- added doc comments
- changed vars ext and src type to Array<String> to match howlerjs implementation. How would you like to deal with these?
- changed onend, onpause, onplay, onfaded from Void->Void to Int->Void in order to receive the sound id.

General:
- changed version to howlerjs 2.0.0-beta.2

### CODE REVIEW

**Comment by KnightMearh** [comment]
Hey, thanks for the update! I diffed it against mine from before to catch some easily missed features that would be great to have - mostly toggling some optional variables and allowing callbacks (onplay, onend, onpause, onfaded) to receive sound id param. I also left a few questions for you on your preferred way to handle a few overloaded functions. Let me know if you have any questions! Thanks!

**Comment by adireddy** [comment]
:+1:

**Comment by adireddy** [comment]
FYI, Just released it to haxelib.

**Comment by KnightMearh** [comment]
Great! TY

**Pull request merged**
